FROM openjdk:8-jdk
MAINTAINER khiempm1 (khiem.pm170084@sis.hust.edu.vn)
COPY MasterScala-1.0-SNAPSHOT-jar-with-dependencies.jar /usr/local/service/
COPY conf /usr/local/service/conf
COPY industry_stock_id_broad_band.txt /usr/local/service/
WORKDIR /usr/local/service/
CMD ["java", "-cp", "MasterScala-1.0-SNAPSHOT-jar-with-dependencies.jar", "com.viettel.vtcc.spark.process.StreamTelegram"]